import { UseSwipiType } from './types';
export declare const useSwipi: ({ config, children, autoplay, dotColor, customDot, showArrows, slidesNumber, autoplaySpeed, dotsAnimation, activeDotColor, slidesAnimation, customActiveDot, spaceBetweenSlides, loop }: UseSwipiType) => {
    slides: import("./types").AddUniqueIdReturnType;
    animation: boolean;
    transform: number;
    slideIndex: number;
    slideWidth: number;
    isShowArrows: boolean;
    spaceBetween: number;
    slidesWrapperRef: import("react").RefObject<HTMLDivElement>;
    Dots: import("react").FunctionComponent<import("../types").DotsTypes>;
    onEnd: () => void;
    onMove: (X: number) => void;
    onStart: (X: number) => void;
    returnDots: (index: number) => import("react").ReactNode;
    setTransform: import("react").Dispatch<import("react").SetStateAction<number>>;
    setAnimation: import("react").Dispatch<import("react").SetStateAction<boolean>>;
    handleDotClick: (index: number) => void;
    nextImg: () => void;
    prevImg: () => void;
    countShowDots: number;
    isDisableButton: (isNext?: boolean) => boolean;
};
